/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as MyWiseRouteImport } from './routes/my-wise'
import { Route as AuthenticatedChangePasswordRouteImport } from './routes/_authenticated/change-password'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedSessionsRouteImport } from './routes/_authenticated/sessions'
import { Route as AboutChairpersonRouteImport } from './routes/about/chairperson'
import { Route as AboutFaqRouteImport } from './routes/about/faq'
import { Route as AboutGoverningBodyRouteImport } from './routes/about/governing-body'
import { Route as AboutVisionRouteImport } from './routes/about/vision'
import { Route as VerifyCodeRouteImport } from './routes/verify.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const MyWiseRoute = MyWiseRouteImport.update({
  id: '/my-wise',
  path: '/my-wise',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedChangePasswordRoute =
  AuthenticatedChangePasswordRouteImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSessionsRoute = AuthenticatedSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AboutChairpersonRoute = AboutChairpersonRouteImport.update({
  id: '/about/chairperson',
  path: '/about/chairperson',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutFaqRoute = AboutFaqRouteImport.update({
  id: '/about/faq',
  path: '/about/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutGoverningBodyRoute = AboutGoverningBodyRouteImport.update({
  id: '/about/governing-body',
  path: '/about/governing-body',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutVisionRoute = AboutVisionRouteImport.update({
  id: '/about/vision',
  path: '/about/vision',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyCodeRoute = VerifyCodeRouteImport.update({
  id: '/verify/$code',
  path: '/verify/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/my-wise': typeof MyWiseRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/sessions': typeof AuthenticatedSessionsRoute
  '/about/chairperson': typeof AboutChairpersonRoute
  '/about/faq': typeof AboutFaqRoute
  '/about/governing-body': typeof AboutGoverningBodyRoute
  '/about/vision': typeof AboutVisionRoute
  '/verify/$code': typeof VerifyCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/my-wise': typeof MyWiseRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/sessions': typeof AuthenticatedSessionsRoute
  '/about/chairperson': typeof AboutChairpersonRoute
  '/about/faq': typeof AboutFaqRoute
  '/about/governing-body': typeof AboutGoverningBodyRoute
  '/about/vision': typeof AboutVisionRoute
  '/verify/$code': typeof VerifyCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/my-wise': typeof MyWiseRoute
  '/_authenticated/change-password': typeof AuthenticatedChangePasswordRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/sessions': typeof AuthenticatedSessionsRoute
  '/about/chairperson': typeof AboutChairpersonRoute
  '/about/faq': typeof AboutFaqRoute
  '/about/governing-body': typeof AboutGoverningBodyRoute
  '/about/vision': typeof AboutVisionRoute
  '/verify/$code': typeof VerifyCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/my-wise'
    | '/change-password'
    | '/portal'
    | '/reports'
    | '/sessions'
    | '/about/chairperson'
    | '/about/faq'
    | '/about/governing-body'
    | '/about/vision'
    | '/verify/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/my-wise'
    | '/change-password'
    | '/portal'
    | '/reports'
    | '/sessions'
    | '/about/chairperson'
    | '/about/faq'
    | '/about/governing-body'
    | '/about/vision'
    | '/verify/$code'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$'
    | '/my-wise'
    | '/_authenticated/change-password'
    | '/_authenticated/portal'
    | '/_authenticated/reports'
    | '/_authenticated/sessions'
    | '/about/chairperson'
    | '/about/faq'
    | '/about/governing-body'
    | '/about/vision'
    | '/verify/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  MyWiseRoute: typeof MyWiseRoute
  AboutChairpersonRoute: typeof AboutChairpersonRoute
  AboutFaqRoute: typeof AboutFaqRoute
  AboutGoverningBodyRoute: typeof AboutGoverningBodyRoute
  AboutVisionRoute: typeof AboutVisionRoute
  VerifyCodeRoute: typeof VerifyCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-wise': {
      id: '/my-wise'
      path: '/my-wise'
      fullPath: '/my-wise'
      preLoaderRoute: typeof MyWiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/change-password': {
      id: '/_authenticated/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AuthenticatedChangePasswordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sessions': {
      id: '/_authenticated/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AuthenticatedSessionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/about/chairperson': {
      id: '/about/chairperson'
      path: '/about/chairperson'
      fullPath: '/about/chairperson'
      preLoaderRoute: typeof AboutChairpersonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/faq': {
      id: '/about/faq'
      path: '/about/faq'
      fullPath: '/about/faq'
      preLoaderRoute: typeof AboutFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/governing-body': {
      id: '/about/governing-body'
      path: '/about/governing-body'
      fullPath: '/about/governing-body'
      preLoaderRoute: typeof AboutGoverningBodyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/vision': {
      id: '/about/vision'
      path: '/about/vision'
      fullPath: '/about/vision'
      preLoaderRoute: typeof AboutVisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$code': {
      id: '/verify/$code'
      path: '/verify/$code'
      fullPath: '/verify/$code'
      preLoaderRoute: typeof VerifyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChangePasswordRoute: typeof AuthenticatedChangePasswordRoute
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSessionsRoute: typeof AuthenticatedSessionsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChangePasswordRoute: AuthenticatedChangePasswordRoute,
  AuthenticatedPortalRoute: AuthenticatedPortalRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSessionsRoute: AuthenticatedSessionsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  MyWiseRoute: MyWiseRoute,
  AboutChairpersonRoute: AboutChairpersonRoute,
  AboutFaqRoute: AboutFaqRoute,
  AboutGoverningBodyRoute: AboutGoverningBodyRoute,
  AboutVisionRoute: AboutVisionRoute,
  VerifyCodeRoute: VerifyCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
