/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as MyWiseRouteImport } from './routes/my-wise'
import { Route as ApiPublicAuthGoogleCallbackRouteImport } from './routes/api/public/auth/google/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MyWiseRoute = MyWiseRouteImport.update({
  id: '/my-wise',
  path: '/my-wise',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuthGoogleCallbackRoute =
  ApiPublicAuthGoogleCallbackRouteImport.update({
    id: '/api/public/auth/google/callback',
    path: '/api/public/auth/google/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/my-wise': typeof MyWiseRoute
  '/api/public/auth/google/callback': typeof ApiPublicAuthGoogleCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/my-wise': typeof MyWiseRoute
  '/api/public/auth/google/callback': typeof ApiPublicAuthGoogleCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/my-wise': typeof MyWiseRoute
  '/api/public/auth/google/callback': typeof ApiPublicAuthGoogleCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$' | '/my-wise' | '/api/public/auth/google/callback'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$' | '/my-wise' | '/api/public/auth/google/callback'
  id: '__root__' | '/' | '/$' | '/my-wise' | '/api/public/auth/google/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  MyWiseRoute: typeof MyWiseRoute
  ApiPublicAuthGoogleCallbackRoute: typeof ApiPublicAuthGoogleCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-wise': {
      id: '/my-wise'
      path: '/my-wise'
      fullPath: '/my-wise'
      preLoaderRoute: typeof MyWiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/google/callback': {
      id: '/api/public/auth/google/callback'
      path: '/api/public/auth/google/callback'
      fullPath: '/api/public/auth/google/callback'
      preLoaderRoute: typeof ApiPublicAuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  MyWiseRoute: MyWiseRoute,
  ApiPublicAuthGoogleCallbackRoute: ApiPublicAuthGoogleCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
